# Generated by Django 5.2.6 on 2025-09-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name=3)),
                ('email', models.EmailField(max_length=100)),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
